// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irffkyksbvalqailrwmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZmZreWtzYnZhbHFhaWxyd214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTE5ODcsImV4cCI6MjA3MjM2Nzk4N30.6bimfeHE6ZxvgC22xt8M-CDoOVF4z12TG-VQNJrWRZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});